# Generated by Django 5.2.1 on 2025-05-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='community_validations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
