# Generated by Django 5.2.1 on 2025-05-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_observation_community_validations'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
