# Generated by Django 5.2.1 on 2025-05-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_observation_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='observations/images/'),
        ),
    ]
