name: bioscout_mobile
description: BioScout Mobile App for biodiversity observations
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  image_picker: ^1.0.2
  connectivity_plus: ^5.0.1
  sqflite: ^2.3.0
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  flutter_dotenv: ^5.1.0
  dio: ^5.3.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 